name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    name: Build Android
    runs-on: self-hosted # Use self-hosted runner for Android
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set up Flutter (Correct Version)
        run: |
          # Install the correct Flutter version matching your Dart SDK version requirement
          curl -LO https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.4.4-stable.tar.xz
          tar -xf flutter_linux_3.4.4-stable.tar.xz
          export PATH="$PATH:$(pwd)/flutter/bin"
          flutter doctor -v
          flutter --version

      - name: Install Dependencies
        run: flutter pub get
      
      - name: Run Build Runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Android APK
        run: flutter build apk --release
      
      - name: Upload Android Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Android-APK
          path: build/app/outputs/flutter-apk/app-release.apk
