name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    name: Build Android
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
      
      - name: Set up Flutter
        run: |
          # Download Flutter 3.4.4 to match your project environment
          curl -LO https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.4.4-stable.tar.xz
          tar -xf flutter_linux_3.4.4-stable.tar.xz
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter --version
          flutter doctor -v

      
      - name: Install Dependencies
        run: flutter pub get
      
      - name: Run Build Runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Android APK
        run: flutter build apk --release
      
      - name: Upload Android Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Android-APK-${{ github.run_number }}
          path: build/app/outputs/flutter-apk/app-release.apk
